Repository pulp/pulp, pull requests merged in 2018-12, with the labels that each got.

#3765 Problem: Some serializers are not available via plugin API.
  plugin/pulpcore/plugin/serializers.py
Labels: 3.0, bugfix, plugin-writer

#3749 Document how to run tests in the development setup
  docs/contributing/dev-setup/index.rst
  docs/contributing/dev-setup/runtests.rst
Labels: 3.0, Documentation, plugin-writer

#3783 Remove 'notes' from Pulp
  .travis/install.sh
  docs/contributing/architecture/app-layout.rst
  docs/contributing/architecture/rest-api.rst
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/app/models/generic.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/content.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/tests/functional/api/test_crud_repos.py
  pulpcore/tests/unit/models/test_generic.py
  pulpcore/tests/unit/models/test_task.py
Labels: 3.0, breaking-changes

#3784 Add installation instructions for mongodb 3.x
  docs/user-guide/installation/fedora.rst
  docs/user-guide/installation/rhel_centos.rst
Labels: Documentation

#3779 Adds the content app to pulpcore.content
  .travis/before_script.sh
  .travis/script.sh
  .travis/server.yaml
  pulpcore/app/models/repository.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/settings.py
  pulpcore/app/urls.py
  pulpcore/app/views/__init__.py
  pulpcore/app/views/content.py
  pulpcore/content/__init__.py
  pulpcore/content/handler.py
  setup.py
Labels: 3.0, breaking-changes, feature, lazy

#3800 Create a new Task field job_id to store rq job ids
  pulpcore/app/models/task.py
  pulpcore/app/response.py
  pulpcore/app/serializers/task.py
  pulpcore/tasking/tasks.py
  pulpcore/tasking/util.py
  pulpcore/tasking/worker.py
  pulpcore/tests/unit/models/test_task.py
Labels: 3.0, breaking-changes

#3802 Align default settings with new content app
  pulpcore/etc/pulp/settings.py
Labels: 3.0, bugfix

#3804 Add docs on lazy to the workflows section
  docs/glossary.rst
  docs/workflows/deferred-download.rst
  docs/workflows/index.rst
  docs/workflows/lazy-downloading.rst
Labels: 3.0, Documentation, lazy

#3774 API Changes
  pulpcore/app/models/repository.py
  pulpcore/app/serializers/__init__.py
  pulpcore/app/serializers/base.py
  pulpcore/app/serializers/repository.py
  pulpcore/app/serializers/task.py
  pulpcore/app/util.py
  pulpcore/app/viewsets/__init__.py
  pulpcore/app/viewsets/content.py
  pulpcore/app/viewsets/custom_filters.py
  pulpcore/app/viewsets/repository.py
  pulpcore/tasking/util.py
  pulpcore/tests/functional/api/using_plugin/constants.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_content_promotion.py
  pulpcore/tests/functional/api/using_plugin/test_orphans.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
  pulpcore/tests/functional/api/using_plugin/test_tasking.py
  pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
  pulpcore/tests/unit/serializers/test_base.py
  pulpcore/tests/unit/test_util.py
Labels: 3.0, breaking-changes, plugin-writer

#3805 Skip over url generation for content types without a viewset
  pulpcore/app/serializers/repository.py
Labels: 3.0

#3797 Adding release notes and bumping version for 3.0.0b17
  docs/release-notes/pulpcore/3.0.x.rst
  setup.py
Labels: 3.0

#3807 Adds importing of the 'content' module
  pulpcore/content/__init__.py
Labels: 3.0, feature, lazy

#3801 Prepend type for master/detail models with a plugin app label
  pulpcore/app/models/base.py
  pulpcore/tests/functional/api/using_plugin/constants.py
Labels: breaking-changes

#3810 Checking in migrations
  .gitignore
  .travis/before_script.sh
  docs/installation/instructions.rst
  pulpcore/app/migrations/0001_initial.py
  pulpcore/app/migrations/__init__.py
Labels: 3.0, breaking-changes
