Repository pulp/pulp, pull requests merged in 2018-04, with the labels that each got.

#3399 "Get the Source" Instructions Omit Working Branch
  docs/contributing/dev-setup/source.rst
Labels: 3.0, Documentation

#3405 Increase sqlite timeout
  .travis/server.sqlite.yaml
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3402 Add worker filtering
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3406 Fix date filtering on tasks and repository versions
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3403 Change how workers are represented
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/serializers/status.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/app/views/status.py
  pulpcore/pulpcore/tasking/services/worker_watcher.py
Labels: 3.0

#3407 Remove ability to delete content units
  pulpcore/pulpcore/app/apps.py
  pulpcore/pulpcore/app/viewsets/__init__.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/content.py
Labels: 3.0

#3408 Simplify travis config as it relates to Django versions
  .travis.yml
  .travis/install.sh
Labels: 3.0

#3401 As a user, I can cleanup orphan content and artifacts
  pulpcore/pulpcore/app/tasks/__init__.py
  pulpcore/pulpcore/app/tasks/orphan.py
  pulpcore/pulpcore/app/urls.py
  pulpcore/pulpcore/app/views/__init__.py
  pulpcore/pulpcore/app/views/orphans.py
  pulpcore/pulpcore/tasking/tasks.py
Labels: 3.0

#3412 Remove non-applicable silenced warning
  pulpcore/pulpcore/app/settings.py
Labels: 3.0

#3416 Don't run tasks on the resource manager
  pulpcore/pulpcore/app/models/task.py
Labels: 3.0

#3411 Add basic unit tests policy
  docs/contributing/index.rst
  docs/contributing/unit_tests.rst
Labels: 3.0, Documentation

#3414 Move tests out of pulpcore/pulpcore/app
  pulpcore/tests/__init__.py
  pulpcore/tests/fields/__init__.py
  pulpcore/tests/fields/test_jsonfield.py
  pulpcore/tests/models/__init__.py
  pulpcore/tests/models/test_generic.py
  pulpcore/tests/serializers/__init__.py
  pulpcore/tests/serializers/test_base.py
  pulpcore/tests/test_settings.py
  pulpcore/tests/viewsets/__init__.py
  pulpcore/tests/viewsets/test_base.py
Labels: 3.0

#3404 Renames Importer to Remote
  .travis/install.sh
  docs/contributing/3.0-development/app-layout.rst
  docs/contributing/3.0-development/data-modeling.rst
  docs/contributing/3.0-development/rest-api.rst
  docs/contributing/language_guide.rst
  docs/plugins/plugin-api/download.rst
  docs/plugins/plugin-writer/basics.rst
  docs/plugins/plugin-writer/checklist.rst
  docs/plugins/plugin-writer/first-plugin.rst
  plugin/pulpcore/plugin/changeset/__init__.py
  plugin/pulpcore/plugin/changeset/main.py
  plugin/pulpcore/plugin/changeset/model.py
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/download/group.py
  plugin/pulpcore/plugin/models/__init__.py
  plugin/pulpcore/plugin/models/remote.py
  plugin/pulpcore/plugin/serializers.py
  plugin/pulpcore/plugin/viewsets.py
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/base.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/app/urls.py
  pulpcore/pulpcore/app/viewsets/__init__.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/tests/viewsets/test_base.py
  test_requirements.txt
Labels: 3.0

#3419 Added back two mixins removed earlier
  pulpcore/pulpcore/app/viewsets/content.py
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0

#3409 Prevent query matching all content/artifact when not criteria included.
  plugin/pulpcore/plugin/changeset/iterator.py
  plugin/pulpcore/plugin/changeset/model.py
Labels: 3.0

#3424 Remote auto_publish field from Publisher
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3423 Rename Remote.feed_url to Remote.url
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3425 Adds 429 Retry Support
  docs/plugins/plugin-api/download.rst
  plugin/pulpcore/plugin/download/base.py
  plugin/pulpcore/plugin/download/http.py
  plugin/setup.py
Labels: 3.0

#3429 Adds WSGI and Architecture Docs
  docs/arch_and_scale/index.rst
  docs/arch_and_scale/webserver.rst
  docs/index.rst
Labels: 3.0

#3428 Filtering overhaul
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/custom_filters.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/pulpcore/app/viewsets/user.py
Labels: 3.0

#3434 DRY up task states
  common/pulpcore/common/__init__.py
  common/pulpcore/common/constants.py
  pulpcore/pulpcore/app/models/progress.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/serializers/fields.py
  pulpcore/pulpcore/tasking/tasks.py
  pulpcore/pulpcore/tasking/util.py
Labels: 3.0

#3437 get_resource() shouldn't accept a non-specific URI
  pulpcore/pulpcore/app/viewsets/base.py
Labels: 3.0, bugfix

#3438 Add more unit tests around NamedModelViewSet
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/tests/viewsets/test_base.py
Labels: 3.0, testing

#3441 Adding some badges to our README
  README
  README.md
Labels: 3.0

#3442 Return a single task for task operations
  .travis/install.sh
  pulpcore/pulpcore/app/response.py
  pulpcore/pulpcore/app/views/orphans.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0

#3444 Fix a worker filtering bug
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3445 Adding guidance around merging PRs with required PRs
  docs/contributing/continuous_integration.rst
Labels: 3.0, Documentation

#3431 Delete tasks in a complete state. fixes #3527
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3446 Fix unit tests link
  docs/contributing/continuous_integration.rst
Labels: 3.0, Documentation

#3439 Register plugin provided urls.py
  pulpcore/pulpcore/app/apps.py
  pulpcore/pulpcore/app/urls.py
Labels: 3.0

#3380 Validate overlapping distribution paths
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/tests/serializers/test_repository.py
Labels: 3.0

#3448 Order list views where applicable
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/progress.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3449 Prevent task deletion with locked resources
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/tests/models/test_task.py
Labels: 3.0

#3436 General cleanup
  pulpcore/pulpcore/app/apps.py
  pulpcore/pulpcore/app/views/content.py
  pulpcore/pulpcore/app/viewsets/__init__.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/content.py
  pulpcore/pulpcore/tasking/celery_instance.py
  pulpcore/pulpcore/tasking/services/manage_workers.py
Labels: 3.0

#3451 Provide more informative invalid base path error
  pulpcore/pulpcore/app/serializers/base.py
Labels: 3.0

#3461 Adding pulp_ansible to list
  docs/plugins/index.rst
Labels: 3.0, Documentation

#3462 Setting the default branch in codecov to 3.0-dev
  codecov.yml
Labels: 3.0

#3472 Add python to the table of available plugins
  docs/plugins/index.rst
Labels: 3.0

#3473 Add from-pulp2 documentation
  docs/overview/from-pulp-2.rst
  docs/overview/index.rst
Labels: 3.0, Documentation

#3474 Fixed broken filtering on a number of viewsets
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0, bugfix

#3475 Switch pulp's default db back to postgres
  .travis.yml
  .travis/before_script.sh
  .travis/script.sh
  .travis/server.sqlite.yaml
  .travis/server.yaml
  docs/installation/instructions.rst
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3477 Add 'created' to repo version serializer
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0, bugfix
