Repository pulp/pulp, pull requests merged in 2018-06, with the labels that each got.

#3513 Redact last_override_config
  docs/user-guide/release-notes/2.16.x.rst
  server/pulp/server/webservices/views/serializers/__init__.py
Labels: bugfix

#3514 Fixes Pulp w/ Mongoengine v0.14.1+
  server/pulp/server/db/model/__init__.py
Labels: bugfix

#3515 Updating docs and configs to use master instead of 3.0-dev
  README.md
  codecov.yml
  common/README.rst
  docs/contributing/continuous-integration.rst
  docs/contributing/dev-setup/source.rst
  docs/contributing/git.rst
  docs/installation/instructions.rst
  docs/plugins/plugin-writer/planning-guide.rst
  plugin/README.rst
  pulpcore/README.rst
Labels: 3.0, Documentation

#3517 Remove installation step for installing RQ by git commit
  .travis/install.sh
  docs/installation/instructions.rst
  pulpcore/setup.py
Labels: 3.0

#3519 Bump pulpcore version to beta5, update docs to reflect this.
  docs/release-notes/plugin_api/0.1.z.rst
  docs/release-notes/pulpcore/3.0.x.rst
  pulpcore/setup.py
Labels: 3.0

#3522 Updating distribution name help text to mention uniqueness
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3520 Ignore missing consumer profile during applicability regeneration
  server/pulp/server/managers/consumer/applicability.py
Labels: bugfix

#3523 Comment DATABASE.
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3524 Add Sync and Publish serializers
  plugin/pulpcore/plugin/serializers.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/tests/serializers/test_repository.py
Labels: 3.0

#3509 Set parsers explicitly for Artifact Viewset
  pulpcore/pulpcore/app/viewsets/content.py
Labels: 3.0, bugfix

#3531 Raise a ValidationError when undefined attributes are passed to an endpoint.
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/content.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/tests/serializers/test_base.py
  pulpcore/tests/serializers/test_repository.py
Labels: Work In Progress

#3535 Allow users to override page size
  pulpcore/pulpcore/app/pagination.py
Labels: 3.0
