Repository pulp/pulp, pull requests merged in 2018-03, with the labels that each got.

#3349 Sqlite3 and some install fixes
  .travis.yml
  docs/installation/instructions.rst
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3356 Adds pulp-smash to travis
  .travis.yml
  .travis/pulp-smash-config.json
Labels: 3.0

#3352 Fix referencing attribute that does not exist
  pulpcore/pulpcore/app/models/task.py
Labels: 3.0

#3359 Run pulp 3 code against pulp_file smoke tests
  .travis.yml
  .travis/before_script.sh
  .travis/install.sh
  .travis/script.sh
Labels: 3.0

#3345 Add section about DNF to consumer docs
  docs/user-guide/consumer-client/introduction.rst
Labels: Documentation

#3362 Expose pulpcore.app.fields.JSONField to plugins
  plugin/pulpcore/plugin/fields.py
Labels: 3.0

#3363 Remove unused task code
  common/pulpcore/common/tags.py
  plugin/pulpcore/plugin/viewsets.py
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/pulpcore/tasking/tasks.py
Labels: 3.0

#3368 Remove http and https options from distributions
  pulpcore/pulpcore/app/models/publication.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3372 Add warning about overlapping distribution base paths
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3374 Added version information for Pulp plugins to Status API
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/views/status.py
Labels: 3.0

#3361 Remove Ansible docs from installer
  docs/installation/instructions.rst
Labels: 3.0, Documentation, bugfix

#3370 Using /var/lib/pulp/tmp instead of /var/cache/pulp
  .travis/before_script.sh
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/etc/pulp/server.yaml
  pulpcore/pulpcore/tasking/celery_app.py
Labels: 3.0

#3376 Set a 20 second timeout for sqlite
  .travis/server.sqlite.yaml
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3371 Validate distribution base paths
  .gitignore
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3373 Allow users to filter by tasks
  pulpcore/pulpcore/app/viewsets/custom_filters.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3386 Remove usage of the Django 'six' module
  pulpcore/pulpcore/app/serializers/user.py
Labels: 3.0

#3387 Remove the 'is_superuser' field from user-facing API
  pulpcore/pulpcore/app/serializers/user.py
Labels: 3.0

#3382 Fixing problems with bad hostnames
  pulpcore/pulpcore/app/serializers/base.py
Labels: 3.0

#3388 Set batch size to 800 to resolve sqlite issues
  plugin/pulpcore/plugin/changeset/iterator.py
Labels: 3.0

#3385 Remove ability to delete a content unit used by a repo version
  pulpcore/pulpcore/app/viewsets/content.py
Labels: 3.0

#3392 Use Python3-style 'super()' instead of Python2-style
  docs/extensions/napoleon_django/docstring.py
  pulpcore/pulpcore/app/apps.py
  pulpcore/pulpcore/app/models/base.py
  pulpcore/pulpcore/app/models/fields.py
  pulpcore/pulpcore/app/models/progress.py
  pulpcore/pulpcore/app/response.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/viewsets/content.py
  pulpcore/pulpcore/exceptions/base.py
  pulpcore/pulpcore/exceptions/http.py
  pulpcore/pulpcore/exceptions/plugin.py
  pulpcore/pulpcore/tasking/tasks.py
Labels: 3.0

#3391 Clean up file on Artifact deletion
  pulpcore/pulpcore/app/models/content.py
Labels: 3.0

#3369 Simplify worker 'online' state tracking
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/tasking/celery_app.py
  pulpcore/pulpcore/tasking/constants.py
  pulpcore/pulpcore/tasking/services/worker_watcher.py
Labels: 3.0

#3367 Make compatible with Django 2.0
  .travis.yml
  .travis/install.sh
  pulpcore/pulpcore/app/fields.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/tests/fields/test_jsonfield.py
  pulpcore/setup.py
Labels: 3.0

#3234 Include filter fields into schema for read actions only
  pulpcore/pulpcore/app/viewsets/base.py
Labels: 3.0, bugfix

#3384 Fixes publishing any repository version
  pulpcore/pulpcore/app/viewsets/base.py
Labels: 3.0
