Repository pulp/pulp, pull requests merged in 2018-11, with the labels that each got.

#3717 Better support for auto-distribution.
  pulpcore/pulpcore/app/models/publication.py
Labels: 3.0

#3733 Use force_close and concurrency restriction
  plugin/pulpcore/plugin/download/base.py
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/download/file.py
  plugin/pulpcore/plugin/download/http.py
  pulpcore/pulpcore/app/models/repository.py
Labels: 3.0, plugin-writer

#3743 Change the default batch size to 50
  plugin/pulpcore/plugin/stages/api.py
  plugin/tests/unit/stages/test_stages.py
Labels: 3.0

#3735 Calculate applicability for multiple content types
  server/pulp/server/db/migrations/0029_applicability_schema_change.py
  server/pulp/server/db/model/consumer.py
  server/pulp/server/managers/consumer/applicability.py
  server/test/unit/server/managers/consumer/test_applicability.py
Labels: feature

#3744 Problem: bulk_create can fail with IntegrityError
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/content_unit_stages.py
  pulpcore/pulpcore/app/models/content.py
Labels: 3.0, plugin-writer

#3764 Problem: Artifact Saver fails to associate existing Artifacts
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/content_unit_stages.py
Labels: 3.0, bugfix

#3775 Formatting fixups
  plugin/pulpcore/plugin/stages/content_unit_stages.py
  pulpcore/pulpcore/app/views/content.py
Labels: 3.0

#3738 Adds 'policy' to Remote
  docs/plugins/plugin-api/download.rst
  plugin/pulpcore/plugin/download/base.py
  plugin/pulpcore/plugin/download/file.py
  plugin/pulpcore/plugin/download/http.py
  plugin/pulpcore/plugin/models/remote.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/declarative_version.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/constants.py
Labels: 3.0, breaking-changes, feature, lazy, plugin-writer, rest-api
