Repository pulp/pulp, pull requests merged in 2018-08, with the labels that each got.

#3567 Fixes #3883 - Log to console by default
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3570 Changing from cursor to page number pagination
  pulpcore/pulpcore/app/pagination.py
Labels: 3.0, breaking-changes

#3560 Move functional tests from pulp-smash into pulp repo
  .travis/before_script.sh
  .travis/install.sh
  .travis/script.sh
  pulpcore/tests/functional/__init__.py
  pulpcore/tests/functional/api/__init__.py
  pulpcore/tests/functional/api/test_api_docs.py
  pulpcore/tests/functional/api/test_auth.py
  pulpcore/tests/functional/api/test_crd_artifacts.py
  pulpcore/tests/functional/api/test_crud_distributions.py
  pulpcore/tests/functional/api/test_crud_repos.py
  pulpcore/tests/functional/api/test_crud_users.py
  pulpcore/tests/functional/api/test_status.py
  pulpcore/tests/functional/api/test_tasks.py
  pulpcore/tests/functional/api/test_workers.py
  pulpcore/tests/functional/api/using_plugin/__init__.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_orphans.py
  pulpcore/tests/functional/api/using_plugin/test_pagination.py
  pulpcore/tests/functional/api/using_plugin/test_repo_version.py
  pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
  pulpcore/tests/functional/api/using_plugin/utils.py
  pulpcore/tests/functional/constants.py
  pulpcore/tests/functional/utils.py
  pulpcore/tests/unit/__init__.py
  pulpcore/tests/unit/fields/__init__.py
  pulpcore/tests/unit/fields/test_jsonfield.py
  pulpcore/tests/unit/models/__init__.py
  pulpcore/tests/unit/models/test_generic.py
  pulpcore/tests/unit/models/test_task.py
  pulpcore/tests/unit/serializers/__init__.py
  pulpcore/tests/unit/serializers/test_base.py
  pulpcore/tests/unit/serializers/test_repository.py
  pulpcore/tests/unit/test_settings.py
  pulpcore/tests/unit/viewsets/__init__.py
  pulpcore/tests/unit/viewsets/test_base.py
  test_requirements.txt
Labels: 3.0

#3574 Provide reasons for skipping tests
  .travis/script.sh
Labels: 3.0, Tests

#3559 Introducing asyncio stages
  __init__.py
  docs/plugins/plugin-api/overview.rst
  docs/plugins/plugin-api/stages.rst
  plugin/__init__.py
  plugin/pulpcore/plugin/stages/__init__.py
  plugin/pulpcore/plugin/stages/api.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/association_stages.py
  plugin/pulpcore/plugin/stages/content_unit_stages.py
  plugin/pulpcore/plugin/stages/declarative_version.py
  plugin/pulpcore/plugin/stages/models.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/app/models/progress.py
Labels: 3.0, feature, plugin-writer

#3582 Add auto_decompress option everywhere
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/download/http.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/declarative_version.py
Labels: 3.0, feature, plugin-writer

#3586 Remove usages of selectors.bug_is_fixed()
  pulpcore/tests/functional/api/test_api_docs.py
  pulpcore/tests/functional/api/test_auth.py
  pulpcore/tests/functional/api/test_crud_distributions.py
  pulpcore/tests/functional/api/test_crud_repos.py
  pulpcore/tests/functional/api/test_crud_users.py
  pulpcore/tests/functional/api/test_workers.py
  pulpcore/tests/functional/api/using_plugin/test_repo_version.py
  pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
Labels: 3.0, Tests

#3580 Fix storage path for published metadata.
  pulpcore/pulpcore/app/models/storage.py
Labels: 3.0, bugfix

#3589 Adds Pulp 3 nightly and beta builds to travis
  .travis.yml
  .travis/docs-builder.py
  .travis/publish_docs.sh
  .travis/pulp-infra.enc
  docs/_templates/layout.html
Labels: 3.0

#3597 Revert "Add auto_decompress option everywhere"
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/download/http.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/declarative_version.py
Labels: 3.0

#3595 Update SELinux policy
  server/selinux/server/pulp-celery.te
  server/selinux/server/pulp-streamer.te
Labels: Work In Progress, bugfix

#3599 Fix DeclarativeVersion timeout error
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/download/file.py
  plugin/pulpcore/plugin/download/http.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
Labels: 3.0, bugfix

#3588 Support redirect in the content application.
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/views/content.py
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0

#3578 Detect more types of errors, and save time
  .travis/script.sh
Labels: 3.0

#3572 Adds description of the date filters format
  pulpcore/pulpcore/app/viewsets/custom_filters.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0

#3601 Allow users to specify a base_version when creating a repo version
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/app/tasks/repository.py
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0

#3561 Problem: OpenAPI schema doesn't use URIs to identify resources
  pulpcore/pulpcore/app/openapigenerator.py
  pulpcore/pulpcore/app/urls.py
Labels: 3.0
