Repository pulp/pulp, pull requests merged in 2018-05, with the labels that each got.

#3480 Prevent duplicate relateive paths within a publication.
  pulpcore/pulpcore/app/models/publication.py
Labels: 3.0

#3487 Update installation instructions
  docs/installation/instructions.rst
Labels: 3.0, Documentation

#3482 Update migration doc.
  docs/installation/instructions.rst
Labels: 3.0

#3454 Replace Celery with RQ
  .travis.yml
  .travis/install.sh
  .travis/pulp-smash-config.json
  .travis/script.sh
  common/pulpcore/common/constants.py
  doc_requirements.txt
  docs/contributing/platform-api/tasking.rst
  docs/installation/instructions.rst
  docs/release-notes/pulpcore/3.0.x.rst
  plugin/pulpcore/plugin/tasking.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/response.py
  pulpcore/pulpcore/app/serializers/status.py
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/tasks/base.py
  pulpcore/pulpcore/app/tasks/orphan.py
  pulpcore/pulpcore/app/tasks/repository.py
  pulpcore/pulpcore/app/views/orphans.py
  pulpcore/pulpcore/app/views/status.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/etc/default/pulp_celerybeat
  pulpcore/pulpcore/etc/default/pulp_workers
  pulpcore/pulpcore/etc/pulp/server.yaml
  pulpcore/pulpcore/exceptions/base.py
  pulpcore/pulpcore/tasking/celery_app.py
  pulpcore/pulpcore/tasking/celery_instance.py
  pulpcore/pulpcore/tasking/connection.py
  pulpcore/pulpcore/tasking/constants.py
  pulpcore/pulpcore/tasking/services/manage_workers.py
  pulpcore/pulpcore/tasking/services/storage.py
  pulpcore/pulpcore/tasking/services/worker_watcher.py
  pulpcore/pulpcore/tasking/tasks.py
  pulpcore/pulpcore/tasking/util.py
  pulpcore/pulpcore/tasking/worker.py
  pulpcore/setup.py
Labels: 3.0

#3488 Have Travis push packages to pypi whenever a pulp3 tags are created
  .travis.yml
  .travis/deploy.sh
Labels: 3.0

#3490 Minor improvements to docs
  docs/contributing/architecture/rest-api.rst
  docs/contributing/continuous-integration.rst
  docs/contributing/pull-request-walkthrough.rst
  docs/glossary.rst
  docs/installation/configuration-files.rst
  docs/installation/instructions.rst
  docs/overview/components/index.rst
  docs/plugins/index.rst
  docs/plugins/plugin-writer/first-plugin.rst
  docs/plugins/plugin-writer/index.rst
  docs/plugins/plugin-writer/planning-guide.rst
Labels: 3.0, Documentation

#3489 Allowing publication to be unset on distributions
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3495 Adds static content docs
  docs/installation/instructions.rst
  docs/overview/components/index.rst
  docs/overview/components/webserver.rst
  pulpcore/pulpcore/etc/pulp/server.yaml
Labels: 3.0, Documentation, bugfix

#3500 Fix indeterministic worker filtering
  pulpcore/pulpcore/app/viewsets/task.py
Labels: 3.0, bugfix

#3501 Update MIDDLEWARE_CLASSES to MIDDLEWARE in settings.py
  pulpcore/pulpcore/app/settings.py
Labels: 3.0

#3479 Fixes using multiple serializers on derived viewsets
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/tests/viewsets/test_base.py
Labels: 3.0

#3498 Consistent names in server.yaml
  .travis/server.yaml
  docs/installation/configuration-files.rst
  docs/installation/instructions.rst
  pulpcore/pulpcore/app/serializers/fields.py
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/views/content.py
  pulpcore/pulpcore/etc/pulp/server.yaml
  pulpcore/pulpcore/tasking/connection.py
  pulpcore/pulpcore/tasking/services/storage.py
  pulpcore/tests/test_settings.py
Labels: 3.0

#3505 Remove pulp's custom FileField serializer
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/fields.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3506 Removes TaskLock
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/task.py
Labels: 3.0

#3508 Fix dependencies for source installation
  plugin/setup.py
  pulpcore/setup.py
Labels: 3.0

#3510 Stop creating QueryDict for async update data
  pulpcore/pulpcore/app/tasks/base.py
Labels: 3.0, bugfix
