Repository pulp/pulp, pull requests merged in 2018-07, with the labels that each got.

#3545 Show correct schema under repository versions
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0, bugfix

#3544 Fix OpenAPI schema for async responses
  plugin/pulpcore/plugin/serializers.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0, bugfix

#3548 Using querysets for add/remove_content methods
  plugin/pulpcore/plugin/changeset/main.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/tasks/repository.py
Labels: 3.0, breaking-changes, plugin-writer

#3551 Update code for new release of django-filter 2.0
  docs/contributing/architecture/rest-api.rst
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/viewsets/content.py
  pulpcore/pulpcore/app/viewsets/custom_filters.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/pulpcore/app/viewsets/user.py
Labels: 3.0

#3536 Use a query param approach for multiple serializers
  pulpcore/pulpcore/app/files.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/app/models/fields.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/serializers/task.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/setup.py
  pulpcore/tests/viewsets/test_base.py
Labels: 3.0

#3552 Add login functionality to the browseable api
  pulpcore/pulpcore/app/urls.py
Labels: 3.0

#3549 Switch to using integer IDs instead of UUIDs
  docs/contributing/architecture/rest-api.rst
  pulpcore/pulpcore/app/models/auth.py
  pulpcore/pulpcore/app/models/base.py
  pulpcore/pulpcore/app/models/generic.py
  pulpcore/pulpcore/app/models/task.py
  pulpcore/pulpcore/app/pagination.py
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/tasks/repository.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/custom_filters.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/tests/viewsets/test_base.py
Labels: 3.0, breaking-changes

#3556 Fix a bunch of bad references in ReST docs
  docs/Makefile
  docs/contributing/architecture/app-layout.rst
  docs/contributing/architecture/rest-api.rst
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/urls.py
  pulpcore/pulpcore/app/viewsets/__init__.py
Labels: 3.0

#3563 Fix typo "Asnyc" -> "Async"
  plugin/pulpcore/plugin/serializers.py
  pulpcore/pulpcore/app/serializers/__init__.py
  pulpcore/pulpcore/app/serializers/base.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/repository.py
Labels: 3.0

#3565 Fix Pulp on Python 3.7
  .travis.yml
  pulpcore/pulpcore/tasking/tasks.py
  pulpcore/setup.py
Labels: 3.0

#3541 Adding help text for FilterSet fields
  pulpcore/pulpcore/app/viewsets/__init__.py
  pulpcore/pulpcore/app/viewsets/base.py
  pulpcore/pulpcore/app/viewsets/content.py
  pulpcore/pulpcore/app/viewsets/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/pulpcore/app/viewsets/user.py
Labels: 3.0
