Repository pulp/pulp, pull requests merged in 2018-10, with the labels that each got.

#3701 Retry in case of some 5XX errors
  plugin/pulpcore/plugin/download/http.py
Labels: 3.0

#3696 Add connection_limit to a Remote
  plugin/pulpcore/plugin/download/factory.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/tests/unit/stages/test_artifactdownloader.py
  pulpcore/pulpcore/app/models/repository.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3704 Make an Artifact from a PulpTemporaryUploadedFile
  docs/plugins/plugin-api/download.rst
  plugin/pulpcore/plugin/download/__init__.py
  plugin/pulpcore/plugin/download/base.py
  plugin/pulpcore/plugin/serializers.py
  pulpcore/pulpcore/app/models/content.py
  pulpcore/pulpcore/exceptions/__init__.py
  pulpcore/pulpcore/exceptions/validation.py
Labels: 3.0, breaking-changes, plugin-writer

#3712 Release notes for 2.17.1
  docs/user-guide/release-notes/2.17.x.rst
Labels: Documentation

#3711 Removes custom User model
  pulpcore/pulpcore/app/management/commands/reset-admin-password.py
  pulpcore/pulpcore/app/models/__init__.py
  pulpcore/pulpcore/app/models/auth.py
  pulpcore/pulpcore/app/serializers/user.py
  pulpcore/pulpcore/app/settings.py
  pulpcore/pulpcore/app/viewsets/user.py
Labels: 3.0, bugfix

#3714 Remove JWT tests
  pulpcore/tests/functional/api/test_auth.py
Labels: 3.0, Tests

#3728 New Flake8 release has new formatting rules
  .travis/docs-builder.py
  flake8.cfg
  pulpcore/pulpcore/app/apps.py
Labels: 3.0, bugfix

#3722 Fix user serializer for custom user model
  pulpcore/pulpcore/app/management/commands/reset-admin-password.py
  pulpcore/pulpcore/app/serializers/user.py
  pulpcore/pulpcore/app/viewsets/user.py
Labels: 3.0, bugfix

#3720 Add tests for Offline workers in status and worker APIs
  pulpcore/tests/functional/api/test_workers.py
Labels: 3.0, Tests
