Repository pulp/pulp, pull requests merged in 2018-09, with the labels that each got.

#3583 Adds doc string and validation for mirror parameter
  plugin/pulpcore/plugin/stages/declarative_version.py
  pulpcore/pulpcore/app/serializers/repository.py
Labels: 3.0

#3594 Update smash-tests w/ changes made to plugin_template
  .travis/install.sh
  .travis/script.sh
  plugin/pulpcore/plugin/models/__init__.py
  pulpcore/pulpcore/app/models/base.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/app/viewsets/task.py
  pulpcore/tests/functional/api/test_crd_artifacts.py
  pulpcore/tests/functional/api/using_plugin/constants.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
  pulpcore/tests/functional/api/using_plugin/test_orphans.py
  pulpcore/tests/functional/api/using_plugin/test_pagination.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
  pulpcore/tests/functional/api/using_plugin/test_tasking.py
  pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
  pulpcore/tests/functional/api/using_plugin/utils.py
  test_requirements.txt
Labels: 3.0, Tests

#3627 Fixing tests after pulp_file change and sphinx options
  docs/conf.py
  pulpcore/tests/functional/api/using_plugin/constants.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_pagination.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
  pulpcore/tests/functional/api/using_plugin/test_tasking.py
  pulpcore/tests/functional/api/using_plugin/utils.py
Labels: 3.0, Tests

#3637 Remove Python 3.5 support
  .travis.yml
  common/setup.py
  docs/contributing/dev-setup/quickstart.rst
  docs/contributing/style-guide.rst
  docs/installation/instructions.rst
  plugin/setup.py
  pulpcore/setup.py
Labels: 3.0

#3645 Rebuild content unit counts after unassociating units from a repo.
  server/pulp/server/managers/repo/unit_association.py
  server/test/unit/server/managers/repo/test_unit_association.py
Labels: bugfix

#3643 Add async batches iterator
  .travis/script.sh
  plugin/pulpcore/plugin/stages/api.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/association_stages.py
  plugin/pulpcore/plugin/stages/content_unit_stages.py
  plugin/tests/unit/stages/__init__.py
  plugin/tests/unit/stages/test_stages.py
  test_requirements.txt
Labels: 3.0, bugfix, plugin-writer

#3654 Add support for pass-through publications.
  pulpcore/pulpcore/app/models/publication.py
  pulpcore/pulpcore/app/serializers/repository.py
  pulpcore/pulpcore/app/views/content.py
Labels: 3.0

#3667 Fix MissingResource arguments
  pulpcore/pulpcore/app/views/content.py
  pulpcore/pulpcore/tasking/util.py
Labels: 3.0

#3631 Reduction of information in response to operation postponed
  pulpcore/pulpcore/app/response.py
  pulpcore/tests/functional/api/test_tasks.py
Labels: 3.0, breaking-changes

#3669 Adds a performance profiler for the Stages API
  docs/installation/configuration.rst
  docs/plugins/plugin-api/overview.rst
  docs/plugins/plugin-api/profiling.rst
  plugin/pulpcore/plugin/stages/__init__.py
  plugin/pulpcore/plugin/stages/api.py
  plugin/pulpcore/plugin/stages/artifact_stages.py
  plugin/pulpcore/plugin/stages/models.py
  plugin/pulpcore/plugin/stages/profiler.py
  pulpcore/pulpcore/app/management/commands/stage-profile-summary.py
  pulpcore/pulpcore/app/settings.py
Labels: 3.0, feature, plugin-writer

#3671 Make publisher for publications optional
  pulpcore/pulpcore/app/models/publication.py
Labels: 3.0, bugfix, plugin-writer
