Repository pulp/pulp, pull requests merged in 2019-01, with the labels that each got.

#3812 Add lots more content app docs
  docs/components.rst
  docs/components/index.rst
  docs/components/webserver.rst
  docs/index.rst
  docs/installation/configuration.rst
Labels: 3.0, Documentation, lazy

#3816 Fix bad pause when serializing repository versions
  pulpcore/app/serializers/repository.py
Labels: 3.0, bugfix

#3817 MySQL doesn't support text fields as indexes
  pulpcore/app/migrations/0001_initial.py
  pulpcore/app/models/repository.py
  pulpcore/app/models/task.py
Labels: 3.0, breaking-changes

#3809 Enable streaming for PublishedArtifacts
  pulpcore/content/handler.py
  pulpcore/tests/functional/api/using_plugin/test_auto_distribution.py
  pulpcore/tests/functional/api/using_plugin/test_content_app.py
Labels: 3.0

#3828 Adding names to tasks
  pulpcore/app/migrations/0002_task_name.py
  pulpcore/app/models/task.py
  pulpcore/app/serializers/task.py
  pulpcore/app/viewsets/task.py
  pulpcore/tasking/tasks.py
Labels: 3.0

#3829 Disallow user creation/update
  pulpcore/app/viewsets/user.py
  pulpcore/tests/functional/api/test_crud_users.py
Labels: 3.0, breaking-changes

#3835 Whitenoise should not write to python dir
  pulpcore/app/settings.py
Labels: 3.0, bugfix

#3826 Content app tries all RemoteArtifacts
  pulpcore/content/handler.py
Labels: 3.0, bugfix, lazy

#3849 Fix indention that Shinx complains about
  pulpcore/tasking/tasks.py
  pulpcore/tests/functional/api/using_plugin/test_crd_publications.py
  pulpcore/tests/functional/api/using_plugin/test_pagination.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
  pulpcore/tests/functional/api/using_plugin/test_tasking.py
  pulpcore/tests/functional/api/using_plugin/test_unlinking_repo.py
Labels: 3.0, Documentation

#3846 Let core decide whether to use "_artifact" or "_artifacts"
  pulpcore/app/serializers/__init__.py
  pulpcore/app/serializers/content.py
  pulpcore/app/serializers/fields.py
  pulpcore/app/viewsets/content.py
  pulpcore/tests/functional/api/using_plugin/test_orphans.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
  pulpcore/tests/unit/content/test_handler.py
Labels: 3.0

#3836 Namespace plugin endpoints with Django app label
  .travis/before_script.sh
  docs/contributing/dev-setup/index.rst
  pulpcore/app/viewsets/base.py
  pulpcore/tests/functional/api/using_plugin/constants.py
  pulpcore/tests/functional/api/using_plugin/test_repo_versions.py
Labels: 3.0, breaking-changes
