Repository pulp/pulp, pull requests merged in 2019-02, with the labels that each got.

#3852 Remove dead code
  pulpcore/app/viewsets/content.py
Labels: 3.0

#3856 Add support for Amazon S3
  docs/installation/configuration.rst
  docs/installation/index.rst
  docs/installation/storage.rst
  pulpcore/app/models/fields.py
  pulpcore/app/settings.py
  pulpcore/content/handler.py
Labels: 3.0, feature

#3859 Revise SELinux recommendation
  docs/installation/instructions.rst
Labels: 3.0, Documentation, bugfix

#3851 Handle non-existent repo case when checking types for applicability
  server/pulp/server/managers/consumer/applicability.py
Labels: bugfix

#3865 Update installation instructions
  docs/installation/instructions.rst
Labels: 3.0, Documentation

#3869 Remove threading from pagination test_content
  pulpcore/tests/functional/api/using_plugin/test_pagination.py
Labels: 3.0, Tests

#3872 Modify response_handler for populate_pulp function
  pulpcore/tests/functional/api/using_plugin/utils.py
Labels: 3.0, Tests

#3814 Combine test coverage
  .coveragerc
  .travis.yml
  .travis/before_script.sh
  .travis/script.sh
  pulpcore/tests/functional/content_with_coverage.py
Labels: 3.0

#3877 Fix 500 error when accessing /pulp/api/v3/ as unauthed user
  pulpcore/app/urls.py
Labels: 3.0

#3878 Fix the publish nightly job
  .travis/publish_docs.sh
Labels: 3.0

#3883 Modify endpoint used by AuthTestCase
  pulpcore/tests/functional/api/test_auth.py
Labels: 3.0, Tests

#3858 Save ContentArtifacts in ContentSerializer
  pulpcore/app/serializers/__init__.py
  pulpcore/app/serializers/content.py
  pulpcore/app/serializers/fields.py
Labels: 3.0, breaking-changes

#3882 Use hyphens for Pulp3' system units name.
  .travis/script.sh
  docs/contributing/dev-setup/runtests.rst
  docs/installation/instructions.rst
  pulpcore/tasking/constants.py
  pulpcore/tasking/services/manage_workers.py
  pulpcore/tasking/services/worker_watcher.py
  pulpcore/tasking/tasks.py
  pulpcore/tasking/worker.py
  pulpcore/tests/functional/api/test_workers.py
Labels: 3.0, breaking-changes

#3890 Add test to verify sync/publish content already in pulp
  pulpcore/tests/functional/api/using_plugin/test_content_path.py
Labels: 3.0, Tests

#3894 Use hyphen on test worker
  pulpcore/tests/functional/api/test_workers.py
Labels: 3.0, Tests

#3892 Refactor ArtifactFileField
  pulpcore/app/models/fields.py
Labels: 3.0

#3893 Add unique index for login
  server/pulp/server/db/manage.py
  server/pulp/server/db/model/__init__.py
Labels: bugfix

#3898 Sync in additive mode by default
  pulpcore/app/serializers/repository.py
Labels: 3.0, breaking-changes
